# پرسش ۴

ماتریس $A$
را همانطور که قبل‌تر گفته شد میسازیم و با روش کمترین مربعات آن‌را روی $b$
حل می‌کنیم. سپس جواب به دست آمده را در $A$
ضرب می‌کنیم تا مطمئن شویم که شبیه به $b$
می‌شود که به این معناست که $b$
در فضای ستونی $A$
قرار دارد۰    
در صورتی که جواب منفی باشد، چنین ماتریس $H$
وجود ندارد۰

In [1]:
using LinearAlgebra


function get_single_flat_col(sz, arr, i)
    mat = zeros(sz)
    mat[:, i] = arr
    return vec(mat)
end

function get_inverter_matrix(mat)
    A = []
    b = []
    sz = size(mat)
    for i = 1:sz[2]
        for j = 1:sz[2]
            push!(A, get_single_flat_col(sz, mat[:, i], j))
            if i == j
                push!(b, 1)
            else
                push!(b, 0)
            end
        end
    end
    A = collect(hcat(A...)')
    b = collect(vcat(b...))
    return A, b
end

function dual_inverter(mat1, mat2)
    A1, b1 = get_inverter_matrix(mat1)
    A2, b2 = get_inverter_matrix(mat2)
    A = [A1; A2]
    b = [b1; b2]
    res = A \ b
    res = reshape(res, size(mat1))
    res = collect(res')
    if norm(I - res * mat1) + norm(I - res * mat2) > 1e-6
        return -1
    end
    return res
end


dual_inverter (generic function with 1 method)

در ادامه کد را روی دو ماتریس داده شده اجرا می‌کنیم و وارون مشترک به دست آمده را نشان می‌دهیم:

In [2]:
G1 = [
    2 3
    1 0
    0 4
    1 1
    -1 2
]
G2 = [
    -3 -1
    -1 0
    2 -3
    -1 -3
    1 2
]

H = dual_inverter(G1, G2)

2×5 Array{Float64,2}:
 -0.278166  2.09441   0.860917   -1.22844  -0.690365
  0.161616  0.227273  0.0808081  -0.30303   0.247475

برای تست نیز، وارون به دست آمده را در دو ماتریس ورودی ضرب می‌کنیم تا از همانی بودن جواب اطمینان حاصل کنیم۰

In [3]:
H*G1

2×2 Array{Float64,2}:
  1.0          1.33227e-15
 -4.44089e-16  1.0

In [4]:
H*G2

2×2 Array{Float64,2}:
 1.0          -1.77636e-15
 5.55112e-16   1.0